version: '3.7'

x-environment: &global-environment
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: supersecret
  DOCKER_INFLUXDB_INIT_ORG: myorg
  DOCKER_INFLUXDB_INIT_BUCKET: mybucket
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 83A24B9B-BBF6-4A19-B9F5-5806D4BA8FBD

services:
  master-node:
    build:
      context: ./master-node
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    environment:
      <<: *global-environment

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      <<: *global-environment
      DOCKER_INFLUXDB_INIT_MODE: setup
      TZ: Etc/UTC
    ports:
      - "8086:8086"

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafanapass  # Change 'grafanapass' to your preferred password
      GF_SECURITY_ADMIN_USER: admin

  ntp:
    image: cturra/ntp
    restart: always
    ports:
      - "123:123/udp"

  graylog:
    image: graylog/graylog:5.2.0-rc.2-1
    volumes:
      - graylog-data:/usr/share/graylog/data
      - graylog-log:/usr/share/graylog/log
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      # Pass is "greylog-password"
      GRAYLOG_ROOT_PASSWORD_SHA2: 7af18da763122b0bf251a6477401e593721e2e68e7dba880dbbfee6c40ab8229
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_MONGODB_URI: mongodb://mongo:27017/graylog
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node

volumes:
  influxdb-data:
  grafana-data:
  mosquitto-data:
  mosquitto-log:
  graylog-data:
  graylog-log:
  mongo-data:
