version: '3.7'

x-environment: &global-environment
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: supersecret
  DOCKER_INFLUXDB_INIT_ORG: myorg
  DOCKER_INFLUXDB_INIT_BUCKET: mybucket
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 83A24B9B-BBF6-4A19-B9F5-5806D4BA8FBD

services:
  master-node:
    build:
      context: ./master-node
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    environment:
      <<: *global-environment

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      <<: *global-environment
      DOCKER_INFLUXDB_INIT_MODE: setup
      TZ: Etc/UTC
    ports:
      - "8086:8086"

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafanapass  # Change 'grafanapass' to your preferred password
      GF_SECURITY_ADMIN_USER: admin

  ntp:
    image: cturra/ntp
    container_name: ntp
    restart: always
    ports:
      - "123:123/udp"

volumes:
  influxdb-data:
  grafana-data:
  mosquitto-data:
  mosquitto-log:
